project:
  type: website
  output-dir: docs

website:
  title: ''

#*******************************************************************************
# Announcement
#*******************************************************************************
  announcement:
    icon: info-circle
    dismissable: false
    content: '**DRAFT** - This website is currently being created and tested. URLs will likely be unstable for some time. Please do not quote from or cite this material. '
    type: danger
    position: below-navbar

#*******************************************************************************
# Top-of-page navigation
#*******************************************************************************
  navbar: 
    logo: 'images/logos/OEDA_Logo_Horizontal_Dark.svg'
    logo-alt: 'Oregon Enterprise Data Analytics'
    background: dark
    search: true
    left: 
      - text: 'Home'
        href: index.qmd
      - text: 'Lab manual'
        href: manual-main.qmd
      - text: 'Council'
        href: council-main.qmd
      - text: 'Projects'
        href: projects-main.qmd
      - text: 'Publications'
      - text: 'Blog'
      - text: 'Data profiles'
        href: data-main.qmd

#*******************************************************************************
# Left-side navigation
# COUNCIL (with params that set defaults for all others)
#*******************************************************************************
  sidebar:
    - title: 'Council'
      style: 'docked'
      background: dark
      contents:
        - text: 'Advisory council home'
          href: council-main.qmd
        - text: 'Council members'
          href: council-members.qmd
        - text: 'Proposal rubric'
          href: council-proposal-rubric.qmd
        - section: 'Council meetings'
          href: council-meetings.qmd
          contents:
            - text: '2025-Q4'
              href: council-meeting-2025-q4.qmd
            - text: '2026-Q1'
              href: council-meeting-2026-q1.qmd
            - text: '2026-Q2'
              href: council-meeting-2026-q2.qmd
            - text: '2026-Q3'
              href: council-meeting-2026-q3.qmd
            - text: '2026-Q4'
              href: council-meeting-2026-q4.qmd
              
#*******************************************************************************
# PROJECTS
#*******************************************************************************
    - title: 'Projects'
      contents:
        - text: 'Current projects'
          href: projects-main.qmd
        - text: 'Starting a project'
          href: projects-flow-initiation.qmd
          
#*******************************************************************************
# DATA Profiles
#*******************************************************************************
    - title: 'Data profiles'
      contents:
        - text: 'Data profiles home'
          href: projects-main.qmd
        - text: 'Starting a project'
          href: projects-flow-initiation.qmd

#*******************************************************************************
# LAB MANUAL
#*******************************************************************************
    - title: 'Lab manual'
      contents:
        - text: 'Lab manual home'
          href: manual-main.qmd
        - section: 'Units'
          contents:
            - text: 'Program evaluation'
              href: manual-progeval.qmd
        - section: 'Meetings'
          contents:
            - text: 'OEDA Team Meetings'
              href: manual-meetings-oeda-team.qmd
        - section: 'Ideation'
          contents:
            - text: 'System 4 Intelligence'
              href: manual-ideation-intelligence.qmd
        - section: 'Product development'
          contents:
          - text: Digital formats
            href: manual-products-formats.qmd
          - text: 'OEDA logos'
            href: manual-products-logos.qmd
        - section: 'Publication & delivery'
          contents:
            - text: 'Quality checks-Research reports'
              href: manual-delivery-qc-research-reports.qmd
            - text: 'GitHub pages websites'
              href: manual-delivery-publishing-github-pages.qmd


format:
  html:
    theme: 
      - flatly
      - oeda.scss
    toc: true
    code-tools: true
    highlight-style: github


resources:
  - images/OEDA_divider_background.svg
  - images/logos/OEDA_Logo_Horizontal.svg
  - images/logos/OEDA_Logo_Horizontal_Dark.svg
  - images/logos/OEDA_Logo_Primary.svg
  - images/logos/OEDA_Logo_Primary_Dark.svg
