project:
  type: website
  output-dir: docs

website:
  title: ''
# Announcement
  announcement:
    icon: info-circle
    dismissable: false
    content: '**DRAFT** - This website is currently being created and tested. URLs will likely be unstable for some time. Please do not quote from or cite this material. '
    type: danger
    position: below-navbar

# Top-of-page navigation
  navbar: 
    logo: 'images/OEDA_Logo_Horizontal_Dark.svg'
    logo-alt: 'Oregon Enterprise Data Analytics'
    background: dark
    search: true
    left: 
      - text: 'Home'
        href: index.qmd
      - text: 'Lab manual'
        href: manual-main.qmd
      - text: 'Council'
        href: council-main.qmd
      - text: 'Projects'
        href: projects-main.qmd
      - text: 'Publications'
      - text: 'Blog'
      - text: 'Data profiles'

#*******************************************************************************
# Left-side navigation
# COUNCIL (with params that set defaults for all others)
#*******************************************************************************
  sidebar:
    - title: 'Council'
      style: 'docked'
      background: dark
      contents:
        - text: 'Council purpose'
          href: council-main.qmd
        - text: 'Council members'
          href: council-members.qmd
        - text: 'Proposal rubric'
          hred: council-proposal-rubric.qmd
        - section: 'Council meetings'
          href: council-meetings.qmd
          contents:
            - text: '2025-Q4'
              href: council-meeting-2025-q4.qmd
            - text: '2026-Q1'
              href: council-meeting-2026-q1.qmd
            - text: '2026-Q2'
              href: council-meeting-2026-q2.qmd
            - text: '2026-Q3'
              href: council-meeting-2026-q3.qmd
            - text: '2026-Q4'
              href: council-meeting-2026-q4.qmd
              
#*******************************************************************************
# PROJECTS
#*******************************************************************************
    - title: 'Projects'
      contents:
        - text: 'Current projects'
          href: projects-main.qmd
        - text: 'Starting a project'
          href: projects-flow-initiation.qmd

#*******************************************************************************
# LAB MANUAL
#*******************************************************************************
    - title: 'Lab manual'
      contents:
        - text: 'Lab manual home'
          href: manual-main.qmd
        - section: 'Product development'
          contents:
          - text: Digital formats
            href: products-formats.qmd
          - text: 'OEDA logos'
            href: products-logos.qmd

  # sidebar:
  #   style: 'docked'
  #   search: true
  #   contents:
  #     - text: 'Home'
  #       href: index.qmd
  #     - section: 'Process'
  #       contents:
  #         - text: 'Idea to project'
  #           href: process-early.qmd
  #     - section: 'Ideation'
  #       contents:
  #         - text: 'System 4 Intelligence'
  #           href: ideation-intelligence.qmd
  #         - text: 'Using the request form'
  #           href: ideation-form.qmd
  #         - text: 'Proposal rubric'
  #           href: ideation-rubric.qmd
  #     - section: 'Product development'
  #       contents:
  #         - text: 'OEDA logos'
  #           href: products-logos.qmd
  #         - text: 'Color palettes'
  #           href: products-palettes.qmd
  #     - section: 'Publication & delivery'
  #       contents:
  #         - text: 'Quality checks-Research reports'
  #           href: delivery-qc-research-reports.qmd
  #         - text: 'GitHub pages websites'
  #           href: delivery-publishing-github-pages.qmd
  #     - section: 'Meetings'
  #       contents:
  #         - text: 'OEDA Advisory Council Meetings'
  #           href: meetings-advisory-council.qmd
  #         - text: 'OEDA Team Meetings'
  #           href: meetings-oeda-team.qmd


format:
  html:
    theme: 
      - flatly
      - oeda.scss
    toc: true
    code-tools: true
    highlight-style: github


resources:
  - images/OEDA_divider_background.svg
  - images/logos/OEDA_Logo_Horizontal.svg
  - images/logos/OEDA_Logo_Horizontal_Dark.svg
  - images/logos/OEDA_Logo_Primary.svg
  - images/logos/OEDA_Logo_Primary_Dark.svg
