---
title: "Using the request form"
author: "Jason Wallin, OEDA-GIS Manager"
---
  
Useful research often starts with a spark--an observation, a question, a comment in a meeting, or a pattern in some data. These sparks can come from anywhere: stakeholders ,audits, internal conversations, or your own insights. But, if they say in our heads or scatterd across notebooks or OneNote pages, we risk losing them.

To make sure we don't miss valuable opportunities, any time that you hear, see, or think of something that could become a research question, project idea, or line of inquiry, please drop it into the request form.

Don't worry about polish. Rough ideas are welcome and encouraged.

## Intentions

*   Lighten the mental load - no need to remember every idea; we can just drop it in and move on
*   Get credit for insights - contributions help shape research agendas and demonstrate thought leadership from program staff, OEDA staff, and others
*   Build momentum - even vague or early-stage ideas can become important projects when they are shared and inspire others
*   Stay aligned - a shared backlog should help us prioritize, avoid duplication, and be more aware of the changing landscape and emerging needs

## What happens after submission

We'll triage submissions regularly--currently fortnightly on Tuesday mornings. In these sessions, we introduce the submissions, open the floor for clarifying questions or early comments, and then we might assign ideas to staff for further development, consultation with subject matter experts, etc.
