---
title: "Program evaluation - Report template"
author: "Michael Menefee, PhD"
---

## Evaluation report template


These shoudl be created as Quarto HTML documents and published to the OEDA website.

## YAML header

* title: Adopt a style that clearly indicates the program or intervention, the dependent variable, the size of the observed effect, the location, and the year
    * E.g. "[Program X] reduces [outcome Y] by [meaningful effect size] (2022-2024 statewide data)"
* date: Publication date of final product
* author: Your name and degree
* institution: Oregon Enterprise Data Analytics
* abstract: No more than 500 words, briefly describing the evaluation questions, intervention evaluated, and key findings.

## Executive summary

The Executive Summary should stand alone as a summary of the key sections of the report and should summarize the content of the full report without adding new information. <!-- The Executive Summary should be two to five pages in length. --> It should summarize the following key points: evaluation purpose, evaluation questions, intervention being evaluated, evaluation methods, and findings, conclusions, and recommendations.

### Evaluation purpose and evaluation questions

This should set out the overarching purpose of the evaluation, and how the findings are expected to be used to inform decisions. This section also describes the evaluation questions (which should be limited to just a few key questions). It can also identify key audiences for the evaluation.

### Background

Enough information should be provided to give sufficient context. However, in the Executive Summary this section can receive less emphasis than it might in the overall report so that more attention can be given to the evaluation purpose, design, limitations, and findings. In the main report, the background section should describe the problem being addressed by the strategy, project, activity, or interventions and the logic for why it will lead to better outcomes. This could include a logical framework for the activity if one exists, and the development hypothesis, or causal logic, of the project or program of which the activity is a part.

### Evaluation design, methods, and limitations

This section describes the overall design, specific data collection and analysis methods linked to the evaluation questions, and limitations of the data, methods, or other issues that affected the findings.

### Findings, conclusions, and recommendations (if applicable)

This section should report those findings based on evidence generated by the evaluation data collection and analysis methods. Findings should be fact-based and not rely only on opinion, even of experts. Conclusions are drawn directly from findings and help summarize the “so what” of the findings. Several findings can lead to one or more conclusions. Whenever possible, data should be presented visually in easy-to-read charts, tables, graphs, and maps to demonstrate the evidence that supports conclusions and recommendations.


```{r}
#| echo: true
#| eval: false

---
title: 'Title'
subtitle: 'Optional subtitle'
date: 'yyyy-mm-dd'
author: 'First Last, Degree'
institution: 'Oregon Enterprise Data Analytics'
abstract: 'Abstract text'
---

## Executive Summary

### Evaluation purpose and evaluation questions
  

  
  
```

